### ISSUE TITLE
Is it possible to create custom loglevels? How can we add filename from which log is made inside the formatter?

### ISSUE THREAD

**Issue by ChanabasanavarVijayKumar** [BeTomorrow/react-native-file-logger#25]
If its possible, please add it in info so that it will be helpful.

**Comment by alois-beto** [comment]
It is not possible because the lib was not intended that way. 

The library has been designed to be integrated into an existing with as little effort as possible, that's why we connect to the existing `console` object.

Log levels are derived from console levels: `console.debug`, `console.info`, `console.warn`, `console.error`.
