### ISSUE TITLE
Change the log filename

### ISSUE THREAD

**Issue by tatiana-lonestone** [BeTomorrow/react-native-file-logger#59]
Hello,

I was wondering if it was possible to add an option to change the file name when sending by e-mail. Maybe it's already possible, but I don't seem to have seen it in the documentation?

Thanks in advance! :)
And thank's for the lib, very easy to use 🙏

**Comment by alois-beto** [comment]
Hello,

Unfortunately at this moment this is not possible to easily rename the log files.

This is because this lib is based on natives libs (Cocoalumberjack for iOS and Logback for Android) and it's easier to let them handle the files management.

But you are not stuck, you can have access to the files with `FileLogger.getLogFilePaths()` and then rename and send it the way you want on your side 🙂
